
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 01 21:03:02 CET 2022
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 35;
  public static final int CTE = 37;
  public static final int CASE = 10;
  public static final int INT = 12;
  public static final int PUNTOCOMA = 9;
  public static final int MINOR = 25;
  public static final int WRITEINT = 14;
  public static final int PRODUCT = 24;
  public static final int ALTERNATIVE = 15;
  public static final int WRITE = 13;
  public static final int CORCHETEIZQ = 32;
  public static final int NOT = 28;
  public static final int AND = 27;
  public static final int ASSIGNWITHSUM = 31;
  public static final int TYPE = 22;
  public static final int NUM = 3;
  public static final int PLUS = 2;
  public static final int ASSIGN = 30;
  public static final int MAIN = 18;
  public static final int IF = 20;
  public static final int CORCHETEDCH = 33;
  public static final int ID = 4;
  public static final int PARENTESISIZQ = 5;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int EQUAL = 26;
  public static final int error = 1;
  public static final int AUTOINCREMENT = 29;
  public static final int COMA = 36;
  public static final int BREAK = 11;
  public static final int VOID = 23;
  public static final int PARENTESISDCH = 6;
  public static final int ELSE = 21;
  public static final int WHILE = 16;
  public static final int LLAVEIZQ = 7;
  public static final int DEFAULT = 17;
  public static final int STRING = 34;
  public static final int LLAVEDCH = 8;
}

